export type ValidSkills =
  | "C#"
  | ".NET"
  | "ASP.NET Core"
  | "Entity Framework Core"
  | "LINQ"
  | "WPF"
  | "NUnit"
  | "SQL"
  | "MSSQL"
  | "PostgreSQL"
  | "MongoDB"
  | "Docker"
  | "Kubernetes"
  | "Azure"
  | "Azure DevOps"
  | "CI/CD"
  | "Git"
  | "Swagger"
  | "Grafana"
  | "Elastic Stack"
  | "Rancher"
  | "React"
  | "Next.js"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "Java"
  | "Python"
  | "R"
  | "AutoML"
  | "Shell"
  | "Singularity"
  | "Scrum"
  | "UML";

export type ValidCategory =
  | "Backend"
  | "Frontend"
  | "Full Stack"
  | "Web Dev"
  | "UI/UX"
  | "Data/ML";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
