export type ValidSkills =
  | "C#"
  | ".NET"
  | "ASP.NET Core"
  | "Entity Framework Core"
  | "LINQ"
  | "WPF"
  | "NUnit"
  | "SQL"
  | "MSSQL"
  | "PostgreSQL"
  | "MongoDB"
  | "Docker"
  | "Kubernetes"
  | "Azure"
  | "Azure DevOps"
  | "CI/CD"
  | "Git"
  | "Swagger"
  | "Grafana"
  | "Elastic Stack"
  | "Rancher"
  | "React"
  | "Next.js"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "Java"
  | "Python"
  | "R"
  | "AutoML"
  | "Shell"
  | "Singularity"
  | "Scrum"
  | "UML"
  | "Software Engineering"
  | "Algorithms"
  | "Data Structures"
  | "Databases"
  | "Object-Oriented Programming"
  | "Mathematics"
  | "Physics"
  | "Analytical Thinking"
  | "Problem Solving"
  | "Clean Architecture"
  | "Quartz"
  | "Temporal"
  | "SignalR"
  | "YARP"
  | "Gridify"
  | "Visual Studio"
  | "Visual Studio Code"
  | "JetBrains Rider";

export type ValidCategory =
  | "Backend"
  | "Frontend"
  | "Full Stack"
  | "Web Dev"
  | "UI/UX"
  | "Data/ML"
  | "Machine Learning";

export type ValidExpType = "Personal" | "Professional" | "Academic";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
